sptbi_booking-new_booking_system/sptbi_booking-new_booking_system/booking/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import reverse
from django.urls.conf import include
from . import views
from .restricted_booking_view import restricted_booking_view, approve_booking, reject_booking, check_booking_updates, api_approve_booking, api_reject_booking
# from . import view_restricted
from .views import book_room
from .tests import test_email
from .admin_api import add_column_api, delete_column_api, delete_booking_api

app_name = 'booking'

urlpatterns = [
    path('', views.booking, name='booking'),
    path('floor/<slug:floor_slug>/', views.floor_booking, name='floor_booking'),
    path('profile/', views.profile, name='profile'),
    path('delete/', views.delete, name='delete_booking'),
    path('save_cell_content/', views.save_cell_content, name='save_cell_content'),
    path('download_excel/', views.download_table_as_excel, name='download_excel'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('change_password/', views.change_password, name='change_password'),
    path('success/', views.success, name='success'),
    path('download_log/', views.download_log, name='download_log'),
    path('download_log2/', views.download_log_2, name='download_log2'),
    path('user_log', views.download_log_user, name="user_download_log"),
    path('add_column/', views.add_column, name='add_column'),
    path('delete_columns/', views.delete_columns, name='delete_columns'),
    path('save_columns/', views.save_columns, name='save_columns'),
    path('save_booking/', views.save_booking, name='save_booking'),
    path('delete_slots/', views.delete_slots, name='delete_slots'),
    path('debug/bookings/', views.debug_bookings, name='debug_bookings'),       # Debug routes
    # path('approve-booking/<int:booking_id>/', views.approve_booking, name='approve-booking'),       # Debug routes
    # path('reject-booking/<int:booking_id>/', views.reject_booking, name='reject-booking'),
    #Email Functionality
    path('book-room/',book_room, name='book_room'),
    path('restricted-booking/<slug:floor_slug>/',restricted_booking_view, name='restricted_booking'),
    # path('booking/restricted-booking/<slug:floor_slug>/',restricted_booking_view, name='restricted_booking'),
    path('approve/<str:token>/', approve_booking, name='approve_booking'),
    path('reject/<str:token>/', reject_booking, name='reject_booking'),
    path('check-updates/', check_booking_updates, name='check_booking_updates'),
    path('api/approve/<str:token>/', api_approve_booking, name='api_approve_booking'),
    path('api/reject/<str:token>/', api_reject_booking, name='api_reject_booking'),
    path('test-email/', test_email, name='test_email'),

    # Admin API endpoints
    path('api/add-column/', add_column_api, name='add_column_api'),
    path('api/delete-column/', delete_column_api, name='delete_column_api'),
    path('api/delete-booking/', delete_booking_api, name='delete_booking_api'),
]

sptbi_booking-new_booking_system/sptbi_booking-new_booking_system/website/urls.py
# """website URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.1/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.conf import settings 
# from django.conf.urls.static import static
# from django.views.static import serve
# from django.contrib import admin
# from django.urls import include, path, re_path

# handler404 = "mainsite.views.my_custom_error_view"
# handler500 = "mainsite.views.my_custom_error_view"
# handler403 = "mainsite.views.my_custom_error_view"
# handler400 = "mainsite.views.my_custom_error_view"

# admin.site.site_header = "SP-TBI Admin"
# admin.site.index_title = "SP-TBI Admin Panel"
# admin.site.site_title = "administration"

# urlpatterns = [
#     re_path(r'^media/(?P<path>.*)$', serve,
#         {'document_root': settings.MEDIA_ROOT}),
#     re_path(r'^static/(?P<path>.*)$', serve,
#         {'document_root': settings.STATIC_ROOT}),
#     path('admin/', admin.site.urls),
#     path('', include('mainsite.urls')),
#     path('tickets/', include('tickets.urls', namespace='tickets')),
#     path('booking/', include('booking.urls', namespace='booking')),
#     path("summernote/", include("django_summernote.urls"))
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



"""website URL Configuration

The urlpatterns list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings 
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib import admin
from django.urls import include, path, re_path

handler404 = "mainsite.views.my_custom_error_view"
handler500 = "mainsite.views.my_custom_error_view"
handler403 = "mainsite.views.my_custom_error_view"
handler400 = "mainsite.views.my_custom_error_view"

admin.site.site_header = "SP-TBI Admin"
admin.site.index_title = "SP-TBI Admin Panel"
admin.site.site_title = "administration"

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
    path('tickets/', include('tickets.urls', namespace='tickets')),
    path('booking/', include('booking.urls', namespace='booking')),
    path("summernote/", include("django_summernote.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sptbi_booking-new_booking_system/sptbi_booking-new_booking_system/booking/views.py
import json
import re
import logging
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from .models import aTimeSlot, Floor, Booking
from django.contrib.auth import login, logout, get_user_model
from django.contrib.auth.models import User
from datetime import datetime, timedelta, timezone
import datetime as dt  # Import datetime module with an alias
from django.urls import reverse
from django.core.paginator import Paginator
from django.db.models import F
import xlsxwriter
from mainsite.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.dateparse import parse_date


# Create your views here.
User = get_user_model()

logger = logging.getLogger(__name__)

def index(request):
    events = Event.objects.all()
    events = sorted(events, key=lambda x: x.orderno)
    visit_counter = Count.objects.get(name="Actual")
    visit_add = Count.objects.get(name="Extra")
    about = About.objects.all()
    count_list = str(visit_counter.count + visit_add.count)
    count = list(count_list)
    pg = Programme.objects.all()
    pg = sorted(pg, key=lambda x: x.orderno)
    # list of times from 9am to 9pm in intervals of 30 mins
    times = ["09.00 am", "09.30 am", "10.00 am", "10.30 am", "11.00 am", "11.30 am", "12.00 pm", "12.30 pm", "01.00 pm", "01.30 pm", "02.00 pm", "02.30 pm",
             "03.00 pm", "03.30 pm", "04.00 pm", "04.30 pm", "05.00 pm", "05.30 pm", "06.00 pm", "06.30 pm", "07.00 pm", "07.30 pm", "08.00 pm", "08.30 pm"]
    date = datetime.now().strftime("%Y-%m-%d")
    status = 0
    user = request.user
    if user.is_authenticated:
        status = User.objects.get(email=user.email).lock
    if request.method == "POST":
        if 'form1' in request.POST:
            date = request.POST.get("dateinput")
            print(date)
        elif 'form2' in request.POST:
            user = request.user
            if not user.is_authenticated:
                return redirect("login")
            selected_ids = request.POST.get('selected_ids')
            if selected_ids == "":
                return redirect('index')
            l = selected_ids.split(",")
            room = 0
            date = request.POST.get('dateinput')
            name = request.POST.get('name')
            month = request.POST.get('month')
            year = request.POST.get('year')
            reason = request.POST.get('reason')
            u = User.objects.get(email=user.email)
            print(u)
            for i in l:
                j = i.split("-")
                slot = j[1]
                room = int(j[2])
                print(slot, room, date)
                b = aTimeSlot.objects.filter(slot=slot, room=room, date=date)
                if b:
                    continue
                else:
                    x = aTimeSlot.objects.create(
                        slot=slot, room=room, date=date, name=name, email=user.email, month=month, year=year, reason=reason)
                    u.free_slots += 0.5
                    x.save()
                    u.save()
                    if u.free_slots == u.total:
                        u.lock = 1
                        u.save()
                        break
            if u.free_slots > u.total:
                u.lock = 1
                u.save()
        elif 'form4' in request.POST:
            date = request.POST.get("dateinput")
    timeslots = aTimeSlot.objects.filter(date=date)
    num = range(24)
    r = range(4)
    return render(request, 'booking.html', {'about': about, 'timeslots': timeslots, 'num': num, 'r': r, 'date': date, 'times': times, 'status': status, 'pg': pg, 'count': count, 'events': events})


def delete_slot(request):
    visit_counter = Count.objects.get(name="Actual")
    visit_add = Count.objects.get(name="Extra")
    events = Event.objects.all()
    # events = sorted(events, key=lambda x: x.orderno)
    count_list = str(visit_counter.count + visit_add.count)
    count = list(count_list)
    pg = Programme.objects.all()
    # pg = sorted(pg, key=lambda x: x.orderno)
    times = ["09.00 am", "09.30 am", "10.00 am", "10.30 am", "11.00 am", "11.30 am", "12.00 pm", "12.30 pm", "01.00 pm", "01.30 pm", "02.00 pm", "02.30 pm",
             "03.00 pm", "03.30 pm", "04.00 pm", "04.30 pm", "05.00 pm", "05.30 pm", "06.00 pm", "06.30 pm", "07.00 pm", "07.30 pm", "08.00 pm", "08.30 pm"]
    date = datetime.now().strftime("%Y-%m-%d")
    if request.method == "POST":
        if 'form1' in request.POST:
            date = request.POST.get("dateinput")
            print(date)
        elif 'form2' in request.POST:
            user = request.user
            if not user.is_authenticated:
                return redirect("login")
            selected_ids = request.POST.get('selected_ids')
            if selected_ids == "":
                return redirect('index')
            l = selected_ids.split(",")
            room = 0
            date = request.POST.get('dateinput')
            u = User.objects.get(email=user.email)
            for i in l:
                j = i.split("-")
                slot = j[1]
                room = int(j[2])
                a = aTimeSlot.objects.filter(slot=slot, room=room, date=date)
                a.delete()
                u.free_slots += 0.5
                u.charges = u.free_slots * -250 if u.free_slots < 0 else 0
    timeslots = aTimeSlot.objects.filter(date=date)
    num = range(24)
    r = range(4)
    return render(request, 'deletecal.html', {'timeslots': timeslots, 'num': num, 'r': r, 'date': date, 'times': times, 'pg': pg, 'count': count, 'events': events})


@login_required
def booking(request):
    """Main booking view that redirects to the first active floor."""
    first_floor = Floor.objects.filter(is_active=True).order_by('order').first()
    if first_floor:
        return redirect('floor_booking', floor_slug=first_floor.slug)
    return render(request, 'booking/no_floors.html')

def floor_booking(request, floor_slug):
    """Handle booking for a specific floor."""
    print("In here")
    floor = get_object_or_404(Floor, slug=floor_slug, is_active=True)
    
    # Get all available floors for the dropdown
    available_floors = Floor.objects.filter(is_active=True).order_by('order')
    
    # Get the date from query params or use today
    date_str = request.GET.get('date', datetime.now().strftime('%Y-%m-%d'))
    try:
        selected_date = datetime.strptime(date_str, '%Y-%m-%d')
    except ValueError:
        selected_date = datetime.now()
    
    # Generate time slots from 9 AM to 8:30 PM in 30-minute intervals
    start_time = datetime.strptime('09:00', '%H:%M')
    end_time = datetime.strptime('20:30', '%H:%M')
    time_slots = []
    current = start_time
    while current <= end_time:
        time_slots.append(current.time())  # Store as time objects
        current += timedelta(minutes=30)
    
    # Get rooms for this floor from the model
    rooms = floor.rooms or [f"Meeting Room 1 - {floor.name}"]
    
    # Get all bookings for this floor on the selected date - NO AUTHENTICATION FILTER
    bookings = Booking.objects.filter(
        floor=floor,
        date=selected_date.date(),      
        # status= 'approved'              #only show approved bookings
    ).select_related('floor')
    
    # Debug logging for booking data
    logger.info(f"Found {bookings.count()} bookings for {floor_slug} on {selected_date.date()}")
    logger.info(f"User is authenticated: {request.user.is_authenticated}")
    
    for booking in bookings:
        logger.info(f"DEBUG: Booking found: room={booking.room}, time={booking.time_slot}, reason='{booking.reason}', date={booking.date}")
    
    # Create a dictionary of booked slots using consistent time format
    booked_slots = {}
    for room in rooms:
        booked_slots[room] = {}
        room_bookings = bookings.filter(room=room)
        for booking in room_bookings:
            time_key = booking.time_slot.strftime('%I:%M %p').lower()  # Format as "h:i am/pm"
            if time_key.startswith('0'):
                time_key = time_key[1:]  # Remove leading zero for hours
            
            logger.info(f"DEBUG: Adding booking to UI: room={room}, time_key='{time_key}', reason='{booking.reason}'")
            # booked_slots[room][time_key] = {
            #     'booked_by': booking.booked_by,
            #     'reason': booking.reason  # Include the reason
            # }
            booked_slots[room][time_key] = {
                'booked_by': booking.user.username if booking.user  else booking.booked_by,
                'user_id' : booking.user.id if booking.user else None,
                'reason': booking.reason,

            }
            
    # After creating the booked_slots dictionary, log its contents
    for room in booked_slots:
        for time_key in booked_slots[room]:
            logger.info(f"DEBUG: Final booked_slots: room={room}, time_key='{time_key}', reason='{booked_slots[room][time_key]['reason']}'")
    
    # Previous and next day for navigation
    prev_day = (selected_date - timedelta(days=1)).strftime('%Y-%m-%d')
    next_day = (selected_date + timedelta(days=1)).strftime('%Y-%m-%d')

    context = {
        'floor': floor,
        'available_floors': available_floors,
        'selected_date': selected_date,
        'time_slots': time_slots,
        'rooms': rooms,
        'booked_slots': booked_slots,
        'prev_day': prev_day,
        'next_day': next_day,
        'user_authenticated': request.user.is_authenticated,
    }
    
    # Log the booking data

sptbi_booking-new_booking_system/sptbi_booking-new_booking_system/booking/templates/booking/profile.html
{% extends 'base.html' %} {% load static %} {% block Title %}Profile
{% endblock %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/bootstrap-icons.min.css"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
  integrity="sha384-...your-integrity-hash...="
  crossorigin="anonymous"
/>
<style>
  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0, 0, 0); /* Fallback color */
    background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */
  }

  /* Modal Content */
  .modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
  }

  /* The Close Button */
  .close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }

  .close:hover,
  .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
  }

  .logs-wrapper{
    display:flex;
    flex-direction: column-reverse;
    justify-content: center;
    align-items: center;
    font-size: 20px;
  color: #1c4386;
  }

  .logs-wrapper select {
    border: 1px solid #ccc;
    border-radius: 5px;
    margin: -1rem 1rem;
    font-family: Poppins;
    padding: 0.5rem;
    cursor: pointer;
}

  .logs-wrapper input[type=month]{
    margin: 0 1rem;
  }

.label-divs{
  height: 40px;
  align-items: center;
  width: 100%;
  justify-content: center;
}

.label-divs h5{
  margin-left: 40px;
  font-size: 20px;
  color: #1c4386;
}

.report-title {
    margin: 15px;
    font-size: 28px;
    font-weight: 500;
    color: #1c4386;
    text-align: center;
}

.user-logs-table{
  border-spacing: 3px;
  font-weight: 500;
}


.user-logs-table td{
  padding: 10px 0;
}

@media (max-width: 980px) {
  .user-p {
        display: flex;
        width: 100%;
        flex-direction: row;
        font-size: 1.5rem;
        margin-bottom: 25px;

    }

  .seperator{
    display: none;
  }

  .user-p .mobile-user-1 .profile h3{
    font-size: 35px;
  } 
  
  .user-p .mobile-user-1 .profile{
    font-size: 30px;
    margin: 20px -6px;
  }  
  
  .user-p .mobile-user-1 .profile i{
    font-size: 30px;
  }

  .user-p .password{
    font-size: 25px;
    margin: 20px 65px;
  }

  .mobile-user-2 {
        display: flex;
        width: 45%;
        height: 100%;
        flex-direction: row;
    }

  .logs-wrapper{
    height: 100%;
  }

  .logs-wrapper form{
    height: 60%;
    margin-bottom: -150px;
    width: 100%;
  }

  .user-logs-table td {
    padding: 20px 15px;
   }

  .report-title{
    margin-top: 85px;
   }

   .logs-wrapper table{
      font-size: 25px;
      margin-top: 35px;
   }

   .logs-wrapper input[type=month]{
    font-size: 14px;
   }

 }

</style>

{% endblock %} 
{% block content %} 
{% if user.is_staff %}
<table class="admin">
  <thead class="thead">
    <th style="width: 5%">&nbsp Sr. No</th>
    <th style="width: 25%"><i class="fas fa-user"></i>&nbsp Startup Name</th>
    <th style="width: 20%"><i class="fas fa-envelope"></i> &nbsp Email</th>
    <th style="text-align: right; width: 10%">
      <i class="fas fa-clock"></i> Hours Used
    </th>
    <th style="text-align: right; width: 15%">
      <i class="fas fa-clock"></i> Total Free Hours
    </th>
    <th style="width: 7.5%">Charges</th>
    <th style="width: 10%">Status</th>
    <th style="width: 7.5%">Edit</th>
  </thead>
  {% for i in objs %}
  <tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ i.company_name }}</td>
    <td>{{ i.email }}</td>
    <td style="text-align: right">{{ i.free_slots }} Hours &nbsp &nbsp</td>
    <td style="text-align: right">{{i.total}} Hours &nbsp &nbsp</td>
    <td>Rs.{% if i.charges %}{{i.charges}}0{% else %}0.00{% endif %}</td>
    <td>
      <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" name="email" id="email" value="{{i.email}}" />
        {% if i.lock == 0 %}
        <input type="hidden" name="lock" id="lock" value="1" />
        <button class="edit-btn" type="submit" name="form4" style="cursor:pointer">
          <i class="fas fa-unlock"></i> Unlocked
        </button>
        {% else %}
        <input type="hidden" name="lock" id="lock" value="0" />
        <button class="edit-btn" type="submit" name="form4" style="cursor:pointer">
          <i class="fas fa-lock"></i> Locked
        </button>
        {% endif %}
      </form>
    </td>
    <form action="" method="POST">
      {% csrf_token %}
      <input type="hidden" name="email" id="email" value="{{i.email}}" />
      <td>
        <button class="edit-btn" type="submit" name="form1" style="cursor:pointer">
          <i class="fas fa-edit"></i> Edit
        </button>
      </td>
    </form>
  </tr>
  {% endfor %}
</table>

<div class="btn-wrapper">
  <button class="download-btn">
    <a class="download-btn" href="{% url 'booking:download_excel' %}" ><i class="fas fa-download"></i> Download Current Month Report</a
    >
  </button>
  
  {% comment %} <button type="button" id="myBtn">Download Excel Report</button> {% endcomment %}
</div>
<div class="seperator">
  <div class="lines">
    <div class="diamond"></div>
  </div>
</div>
<div class="logs-wrapper">
  <form method="POST" action="{% url 'booking:download_log2' %}">
      {% csrf_token %}
      <table style="border-spacing: 30px;">
        <tr>
          <td>Company</td>
          <td>   
               <select name="selected" id="mySelect">
            <option value="all" name="option">All companies</option>
            {% for c in companies %}
            <!-- <option value="{{c.name}}" name="option">{{c.name}}</option> -->
             <option value="{{c}}" name="option">{{c}}</option>
            {% endfor %}
        </select>
      </td>
        </tr>
      <!-- <br><br> -->
      <tr>
        <td>Start Month</td>
        <td><input type="month" name="start" required></td>
      </tr>

      <tr>
        <td>End Month</td>
        <td><input type="month" name="end" required></td>
      </tr>
      <!-- <br><br> -->
    </table>
    <center>
      <input class="download-btn logs-dtbn" style="cursor:pointer" type="submit" value="Download User logs"> <br>
    </center>
  </form>


  <h3 class="report-title">Get Custom Report</h3>

</div>
{% else %}
<div class="user-profile">
  <div class="user-p">
    <div class="mobile-user-1">
    <div class="profile">
      {% if user.logo}
      <img src="{{user.logo.url}}" alt="profile" />
      {% endif %} 
      <h3 style="color: #1c4386">{{user.company_name}}</h3>
    </div>
    <div class="profile">
      <i class="fas fa-envelope"></i>
      {{user.email}}
    </div>
    <div class="profile">
      <i class="fas fa-clock"></i>
      Hours Used: {{free_hours}} Hours
    </div>
    <div class="profile">
      <i class="fas fa-clock"></i>
      Free Hours: {{total}} Hours
    </div>
    <div class="profile">
      <i class="bi bi-currency-rupee"></i>
      Charges: Rs.{{charges}}0
    </div>
    <div class="password">
      <a href="{% url 'booking:change_password' %}">
        <i class="fas fa-key"></i>
        Change Password
      </a>
    </div>
    <center>
    <a class="password" href="{% url 'booking:download_log' %}" download style="text-decoration: none;">Download {% now "M"%} Logs</a> 
  </center>
  </div>
    <div class="seperator" style="margin-top:25px;margin-bottom: 25px;">
      <div class="lines" style="width: 236px;">
        <div class="diamond"></div>
      </div>
    </div>
    <div class="mobile-user-2">
    <div class="logs-wrapper">
      <form method="POST" action="{% url 'booking:user_download_log' %}">
          {% csrf_token %}
          <table class="user-logs-table">
          <!-- <br><br> -->
          <tr>
            <td>Start Month</td>
            <td><input type="month" name="start" required></td>
          </tr>
    
          <tr>
            <td>End Month</td>
            <td><input type="month" name="end" required></td>
          </tr>
        </table>
        <center>
          <input class="password" style="cursor:pointer" type="submit" value="Download"> <br>
        </center>
        </form>
    
      <h3 class="report-title" style="margin: -2px;">Get Custom Log</h3>
    </div>
  </div>
  </div>
  <div class="right-section">
    <div class="booking-log">
      <h2>
        Booking Log
      </h2>
      <ul class="log-list">
        <li>
          <table class="date-list">
            <thead>
              <th style="width: 14%">
                <i class="fas fa-calendar"></i> &nbsp Date
              </th>
              <th style="width: 12%">
                <i class="fas fa-clock"></i> &nbsp Slot
              </th>
              <th style="width: 27%">
                <i class="fas fa-building"></i> &nbsp Room
              </th>
              <th><i class="fas fa-bullseye"></i> &nbsp Reason</th>
            </thead>
            {% for i in logs %} {% if i.room == 0 %}
            <tr>
              <td>{{i.date}}</td>
              <td>{{i.slot}}</td>
              <td>Meeting Room 1 - 1st Floor</td>
              <td>{{i.reason}}</td>
            </tr>
            {% elif i.room == 1 %}
            <tr>
              <td>{{i.date}}</td>
              <td>{{i.slot}}</td>
              <td>Meeting Room 1 - 2nd Floor</td>
              <td>{{i.reason}}</td>
            </tr>
            {% elif i.room == 2 %}
            <tr>
              <td>{{i.date}}</td>
              <td>{{i.slot}}</td>
              <td>Meeting Room 2 - 2nd Floor</td>
              <td>{{i.reason}}</td>
            </tr>

            {% else %}
            <tr>
              <td>{{i.date}}</td>
              <td>{{i.slot}}</td>
              <td>Meeting Room - 8th Floor</td>
              <td>{{i.reason}}</td>
            </tr>
            {% endif %} {% endfor %}
          </table>
        </li>
      </ul>
    </div>
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; First</a>
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
</div>


{% endblock content%} 
{% block js %}
<script src="{% static 'js/profile.js'%}"></script>

  
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
  crossorigin="anonymous"
></script>
{% endblock %}